apiVersion: apps/v1
kind: Deployment
metadata:
  name: claims-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: claims-service
  template:
    metadata:
      labels:
        app: claims-service
    spec:
      containers:
        - name: claims-service
          image: rohit8020/claims-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: claims-config
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: AUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: CLAIMS_CLIENT_SECRET
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            periodSeconds: 10
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8083
            periodSeconds: 10
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8083
            periodSeconds: 20
            timeoutSeconds: 3
          resources:
            requests:
              cpu: 200m
              memory: 384Mi
            limits:
              cpu: 750m
              memory: 768Mi
