apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: insurance-platform-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - insurance.local
      secretName: insurance-platform-tls
  rules:
    - host: insurance.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 8080
