apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: Root@123Password!
  MYSQL_DATABASE: authdb
  MYSQL_USER: auth_user
  MYSQL_PASSWORD: Auth@123Password!
