server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: policy-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/policydb}
    username: ${SPRING_DATASOURCE_USERNAME:policy_user}
    password: ${SPRING_DATASOURCE_PASSWORD:Policy@123Password!}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

management:
  endpoints:
    web:
      exposure:
        include: health,info

jwt:
  secret: ${JWT_SECRET:my-super-secret-key-that-is-at-least-32-characters}

app:
  kafka:
    policy-topic: ${POLICY_EVENTS_TOPIC:policy-events}
  internal-api-key: ${INTERNAL_API_KEY:internal-shared-key}
