apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: rohit8020/api-gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: gateway-config
                  key: SERVER_PORT
            - name: SPRING_DATA_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: gateway-config
                  key: SPRING_DATA_REDIS_HOST
            - name: SPRING_DATA_REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: gateway-config
                  key: SPRING_DATA_REDIS_PORT
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: gateway-config
                  key: AUTH_SERVICE_URL
            - name: POLICY_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: gateway-config
                  key: POLICY_SERVICE_URL
            - name: CLAIMS_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: gateway-config
                  key: CLAIMS_SERVICE_URL
            - name: LOGIN_RATE_LIMIT
              valueFrom:
                configMapKeyRef:
                  name: gateway-config
                  key: LOGIN_RATE_LIMIT
            - name: CLAIM_SUBMIT_RATE_LIMIT
              valueFrom:
                configMapKeyRef:
                  name: gateway-config
                  key: CLAIM_SUBMIT_RATE_LIMIT
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: JWT_SECRET
