apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
data:
  SERVER_PORT: "8081"
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/authdb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
  SPRING_DATASOURCE_USERNAME: auth_user
  JWT_ISSUER: http://auth-service:8081
  JWT_KEY_ID: auth-service-rsa-key
  CLAIMS_CLIENT_ID: claims-service
  ZIPKIN_ENDPOINT: http://zipkin:9411/api/v2/spans
