apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
data:
  01-create-service-databases.sql: |
    create database policydb owner policy_user;
    create database claimsdb owner policy_user;
